### ISSUE TITLE
Bug: Vespa not starting

### ISSUE THREAD

**Issue by JayGhiya** [unoplat/vespa-helm-charts#1]
the issue is:

>vespa-0    9    -    vespa-start-configserver    warning    only these hosts should run a config server: [vespa-0.vespa.defau │ this host [vespa-0] should not run a config server                                                                                                

What was followed: [vespa single node minikube setup](https://docs.vespa.ai/en/operations-selfhosted/using-kubernetes-with-vespa.html)

here are the contents after running helm template:

```
# Source: vespa/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: document-index-service
  labels:
    helm.sh/chart: vespa-0.1.0
    app.kubernetes.io/name: vespa
    app.kubernetes.io/instance: vespa
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer
  ports:
    - port: 19071
      targetPort: 19071
      protocol: TCP
      name: vespa-tenant-port
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: vespa-port    
  selector:
    app.kubernetes.io/name: vespa
    app.kubernetes.io/instance: vespa
---
# Source: vespa/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vespa
  labels:
    helm.sh/chart: vespa-0.1.0
    app.kubernetes.io/name: vespa
    app.kubernetes.io/instance: vespa
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vespa
  template:
    metadata:
      labels:
        helm.sh/chart: vespa-0.1.0
        app.kubernetes.io/name: vespa
        app.kubernetes.io/instance: vespa
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
        app: vespa
    spec:
      serviceAccountName: default
      securityContext:
        null
      containers:
        - name: vespa
          securityContext:
            runAsUser: 1000
          image: "vespaengine/vespa:8.277.17"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 19071
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /state/v1/health
              port: 19071
              scheme: HTTP
          resources:
            limits:
              cpu: 2500m
              memory: 5000Mi
            requests:
              cpu: 1000m
              memory: 3000Mi
          volumeMounts:
            - mountPath: /opt/vespa/var/
              name: vespa-storage
          env:
          - name: VESPA_CONFIGSERVERS 
            value: vespa-0.vespa.default.svc.cluster.local
            
  volumeClaimTemplates:
  - metadata:
      name: vespa-storage
    spec:
      accessModes: [ReadWriteOnce]
      resources:
        requests:
          storage: 1Gi
```
Post running helm template it does match with the documentation configuration for single. node but it does not work. i tried with barebone yamls and they do work so not able to understand.
