### ISSUE TITLE
Can't specify storageClassName

### ISSUE THREAD

**Issue by clayrosenthal** [unoplat/vespa-helm-charts#21]
I have a non-default storage class I want to use with this chart and you can't change the storage class name

currently in `templates/statefulset.yaml`:
```
  volumeClaimTemplates:
  {{- range .Values.volumeClaimTemplates }}
  - metadata:
      name: {{ .metadata.name }}
    spec:
      accessModes: {{ .spec.accessModes }}
      resources:
        requests:
          storage: {{ .spec.resources.requests.storage }}
  {{- end }}
```
